# Generated by Django 5.0.6 on 2024-10-31 16:43

from django.db import migrations

def update_old_column(apps, schema_editor):
    CollectionColumn = apps.get_model('data_map_backend', 'CollectionColumn')
    for column in CollectionColumn.objects.all():
        column.module = "llm"
        column.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_old_column),
    ]
