name: vsm_staging
services:
  backend-staging:
    image: visual_data_map/backend
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - quiddity_data:/data
    environment:
      - data_backend_host=http://localhost:55125
      - postgres_host=postgres-staging
      - BACKEND_AUTHENTICATION_SECRET
      - backend_host=http://localhost:55125
      - GPU_UTILITY_SERVER_URL=http://gpu-utility-server:55180
      - vector_database_host=qdrant
      - search_engine_host=opensearch
      - PDFERRET_BASE_URL=http://pdferret:80
      - LOCAL_MODEL_SERVER_URL=http://infinity-model-server:55181
  webserver-staging:
    image: visual_data_map/webserver
    build:
      context: ./frontend
      dockerfile: ../docker/webserver.Dockerfile
    ports:  # this should be the only port in this docker compose setup that is exposed to the outside (except DB dashboards)
      - "${WEBSERVER_STAGING_EXPOSED_IP_V4:-127.0.0.1}:55440:55140"
      - "${WEBSERVER_STAGING_EXPOSED_IP_V6:-[::1]}:55440:55140"
    environment:
      - backend_host=http://backend-staging:55125
  postgres-staging:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=visdatamap
volumes:
  quiddity_data:
  postgres_data:
networks:
  default:
    external: true
    name: visualdatamapnetwork
