services:
  organization-backend-staging:
    image: visual_data_map/organization_backend
    build:
      context: ./
      dockerfile: ./docker/organization_backend.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55425:55125"
    environment:
      - data_backend_host=http://data-backend:55423
  data-backend-staging:
    image: visual_data_map/data_backend
    build:
      context: ./
      dockerfile: ./docker/data_backend.Dockerfile
    volumes:
      - ./:/source_code/
      - /data:/data
    ports:
      - "55423:55123"
    depends_on:
      - organization-backend-staging
    environment:
      - model_server_host=http://model-server:55180
      - infinity_server_host=http://infinity-model-server:55181
      - organization_backend_host=http://organization-backend-staging:55125
      - vector_database_host=qdrant
      # - object_storage_host=mongo
      - search_engine_host=opensearch
      - ABSCLUST_TYPESENSE_DB_API_KEY
      - ABSCLUST_TYPESENSE_DB_HOST
  webserver-staging:
    image: visual_data_map/webserver
    build:
      context: ./frontend
      dockerfile: ../docker/webserver.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55440:55140"
    environment:
      - organization_backend_host=http://organization-backend-staging:55125
      - data_backend_host=http://data-backend-staging:55123
networks:
  default:
    name: visualdatamapnetwork
