name: vsm_showcase
services:
  backend-showcase:
    image: visual_data_map/backend
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
    volumes:
      - ./:/source_code/
      - "${DATA_PATH:-/datia}:/data"
      - ${HOME}/.config/gcloud/application_default_credentials.json:/app/pdferret/application_default_credentials.json
    environment:
      - data_backend_host=http://localhost:55125
      - postgres_host=postgres-showcase
      - BACKEND_AUTHENTICATION_SECRET
      - model_server_host=http://model-server:55180
      - infinity_server_host=http://infinity-model-server:55181
      - backend_host=http://localhost:55125
      - vector_database_host=qdrant
      - search_engine_host=opensearch
      - PDFERRET_BASE_URL=http://pdferret:80
      - PDFERRET_GROBID_URL=http://grobid:8070
      - PDFERRET_TIKA_SERVER_URL=http://tika:9998
      - TIKA_SERVER_ENDPOINT=http://tika:9998
      - TIKA_CLIENT_ONLY=True
      - GOOGLE_APPLICATION_CREDENTIALS=/app/pdferret/application_default_credentials.json
  webserver-prod-showcase:
    image: visual_data_map/webserver_prod
    build:
      context: ./frontend
      dockerfile: ../docker/webserver_prod.Dockerfile
    volumes:
      - ./:/source_code/
    ports:  # this should be the only port in this docker compose setup that is exposed to the outside (except DB dashboards)
      - "${WEBSERVER_STAGING_EXPOSED_IP:-127.0.0.1}:55441:55140"
    environment:
      - backend_host=http://backend-showcase:55125
  postgres-showcase:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=visdatamap
volumes:
  model_server_cache:
  qdrant_storage:
  opensearch_data:
  postgres_data:
  infinity_model_cache:
  swag_data:
networks:
  default:
    name: visualdatamapnetwork
