services:
  model-server:
    image: visual_data_map/model_server
    build:
      context: ./
      dockerfile: ./docker/model_server.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55180:55180"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  organization-backend:
    image: visual_data_map/organization_backend
    build:
      context: ./
      dockerfile: ./docker/organization_backend.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55125:55125"
  data-backend:
    image: visual_data_map/data_backend
    build:
      context: ./
      dockerfile: ./docker/data_backend.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55123:55123"
    depends_on:
      - organization-backend
    environment:
      - model_server_host=http://model-server:55180
      - organization_backend_host=http://organization-backend:55125
      - vector_database_host=qdrant
      - object_storage_host=mongo
      - search_engine_host=opensearch
  webserver:
    image: visual_data_map/webserver
    build:
      context: ./frontend
      dockerfile: ../docker/webserver.Dockerfile
    volumes:
      - ./:/source_code/
    ports:
      - "55140:55140"
    environment:
      - organization_backend_host=http://organization-backend:55125
      - data_backend_host=http://data-backend:55123
  qdrant:
    image: "qdrant/qdrant:latest"
    ports:
      - "6333:6333"
  opensearch:
    image: "opensearchproject/opensearch:latest"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  mongo:
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"
