[tool.poetry]
name = "visual-data-map"
version = "0.1.0"
description = ""
authors = ["Tim Henning <tim@luminosuslight.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.0,<3.12"
flask = "*"
flask-cors = "*"
torch = "*"
transformers = "*"
scikit-learn = "*"
hdbscan = "*"
openai = "*"
gensim = "*"
django = "*"
django-extensions = "*"
djangoql = "*"
django-simple-history = "*"
djangorestframework = "*"
markdown = "*"
django-filter = "*"
drf-social-oauth2 = "*"
social-auth-app-django = "*"
django-cors-headers = "*"
django-jazzmin = "*"
qdrant-client = "*"
opensearch-py = "*"
django-jsonsuit = "*"
pillow = "*"
sentence-transformers = "*"
django-object-actions = "*"
cbor2 = "*"
diskcache = "*"
django-import-export = "*"
beautifulsoup4 = "*"
psycopg2-binary = "*"
scipdf = {git = "https://github.com/Trel725/scipdf_parser"}
umap-learn = {git = "https://github.com/luminosuslight/umap_with_progress_callback.git"}
pypdfium2 = "*"
unstructured-client = "*"
cohere = "*"
scipy = "==1.10.1"
nltk = "*"
pandas = "*"
#pypdf = "*"
pyspellchecker = "*"
#unstructured = {extras = ["pdf"], version = "*"}
lingua-language-detector = "*"
#ocrmypdf = "*"
pdferret = {git = "https://trel725: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@github.com/Trel725/pdferret.git"}
groq = "*"
ratelimit = "*"
pacmap = "*"
cuml-cu12 = {version = "24.6.*", source = "nvidia"}
cachetools = "*"
django-prometheus = "*"
django_ninja = "*"


[tool.poetry.group.dev.dependencies]
viztracer = "*"
spacy = "*"

[[tool.poetry.source]]
name = "pypi"
priority = "primary"

[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
