# Generated by Django 4.2.5 on 2023-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectschema',
            name='default_search_fields',
            field=models.ManyToManyField(blank=True, help_text='For combined search', null=True, related_name='+', to='data_map_backend.objectfield', verbose_name='Default Search Fields'),
        ),
    ]
