# Generated by Django 4.2.5 on 2023-11-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='generator',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar', null=True, verbose_name='Text Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='historicalgenerator',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='historicalgenerator',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar', null=True, verbose_name='Text Similarity Threshold'),
        ),
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar (overriding the generators value)', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar (overriding the generators value)', null=True, verbose_name='Text Similarity Threshold'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar (overriding the generators value)', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar (overriding the generators value)', null=True, verbose_name='Text Similarity Threshold'),
        ),
    ]
