# Generated by Django 4.2.5 on 2023-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0003_remove_generator_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingspace',
            name='dimensions',
            field=models.IntegerField(default=0, help_text='Vector size of the embedding', verbose_name='Dimensions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalembeddingspace',
            name='dimensions',
            field=models.IntegerField(default=0, help_text='Vector size of the embedding', verbose_name='Dimensions'),
            preserve_default=False,
        ),
    ]
