# Generated by Django 4.2.4 on 2023-08-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0004_alter_objectfield_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjectfield',
            name='index_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='Index Parameters'),
        ),
        migrations.AddField(
            model_name='historicalobjectfield',
            name='vector_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vector Size'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='index_parameters',
            field=models.TextField(blank=True, null=True, verbose_name='Index Parameters'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='vector_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vector Size'),
        ),
    ]
