# Generated by Django 5.0.6 on 2024-05-29 20:14

import data_map_backend.models
import django.db.models.deletion
from django.db import migrations, models

# object field: es, generator


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0004_replace_int_ids_with_str_identifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generator',
            name='embedding_space',
        ),
        migrations.RemoveField(
            model_name='historicalgenerator',
            name='embedding_space',
        ),
        migrations.AddField(
            model_name='generator',
            name='embedding_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_map_backend.embeddingspace', verbose_name='Embedding Space'),
        ),
        migrations.AddField(
            model_name='historicalgenerator',
            name='embedding_space',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.embeddingspace', verbose_name='Embedding Space'),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='applicable_import_converters',
        ),
        migrations.AddField(
            model_name='dataset',
            name='applicable_import_converters',
            field=models.ManyToManyField(
                verbose_name="Applicable Import Converters",
                to='ImportConverter',
                related_name='+',
                blank=True),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='applicable_export_converters',
        ),
        migrations.AddField(
            model_name='dataset',
            name='applicable_export_converters',
            field=models.ManyToManyField(
                verbose_name="Applicable Export Converters",
                to='ExportConverter',
                related_name='+',
                blank=True),
        ),
        migrations.RemoveField(
            model_name='objectfield',
            name='embedding_space',
        ),
        migrations.RemoveField(
            model_name='historicalobjectfield',
            name='embedding_space',
        ),
        migrations.AddField(
            model_name='objectfield',
            name='embedding_space',
            field=models.ForeignKey(
                verbose_name="Embedding Space",
                help_text="If not set, embedding space of generator will be used",
                to='EmbeddingSpace',
                on_delete=models.PROTECT,
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='historicalobjectfield',
            name='embedding_space',
            field=models.ForeignKey(
                verbose_name="Embedding Space",
                help_text="If not set, embedding space of generator will be used",
                to='EmbeddingSpace',
                on_delete=models.PROTECT,
                blank=True,
                null=True),
        ),
        migrations.RemoveField(
            model_name='objectfield',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='historicalobjectfield',
            name='generator',
        ),
        migrations.AddField(
            model_name='objectfield',
            name='generator',
            field=models.ForeignKey(
                verbose_name="Generator",
                to='Generator',
                on_delete=models.PROTECT,
                blank=True,
                null=True),
        ),
        migrations.AddField(
            model_name='historicalobjectfield',
            name='generator',
            field=models.ForeignKey(
                verbose_name="Generator",
                to='Generator',
                on_delete=models.PROTECT,
                blank=True,
                null=True),
        ),
        migrations.RemoveField(
            model_name='trainedclassifier',
            name='embedding_space',
        ),
        migrations.AddField(
            model_name='trainedclassifier',
            name='embedding_space',
            field=models.ForeignKey(
                verbose_name="Embedding Space",
                to='EmbeddingSpace',
                default='intfloat/e5-base-v2',  # type: ignore
                related_name='+',
                on_delete=models.PROTECT,
                blank=False,
                null=False),
        ),
        migrations.AlterField(
            model_name='trainedclassifier',
            name='embedding_space',
            field=models.ForeignKey(
                verbose_name="Embedding Space",
                to='EmbeddingSpace',
                related_name='+',
                on_delete=models.PROTECT,
                blank=False,
                null=False),
        ),
        migrations.AlterField(
            model_name='collectioncolumn',
            name='identifier',
            field=models.CharField(default=data_map_backend.models.get_random_string, help_text='Do not change this after being used elsewhere', max_length=200, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='applicable_export_converters',
            field=models.ManyToManyField(blank=True, related_name='+', to='data_map_backend.exportconverter', verbose_name='Applicable Export Converters'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='applicable_import_converters',
            field=models.ManyToManyField(blank=True, related_name='+', to='data_map_backend.importconverter', verbose_name='Applicable Import Converters'),
        ),
        migrations.AlterField(
            model_name='embeddingspace',
            name='identifier',
            field=models.CharField(help_text='Do not change this after being used elsewhere', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='exportconverter',
            name='identifier',
            field=models.CharField(help_text='Do not change this after being used elsewhere', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='identifier',
            field=models.CharField(help_text='Do not change this after being used elsewhere', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalembeddingspace',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Do not change this after being used elsewhere', max_length=200, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalexportconverter',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Do not change this after being used elsewhere', max_length=200, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalgenerator',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Do not change this after being used elsewhere', max_length=200, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalimportconverter',
            name='identifier',
            field=models.CharField(db_index=True, help_text='Do not change this after being used elsewhere', max_length=200, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='embedding_space',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If not set, embedding space of generator will be used', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.embeddingspace', verbose_name='Embedding Space'),
        ),
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='generator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.generator', verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='importconverter',
            name='identifier',
            field=models.CharField(help_text='Do not change this after being used elsewhere', max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='embedding_space',
            field=models.ForeignKey(blank=True, help_text='If not set, embedding space of generator will be used', null=True, on_delete=django.db.models.deletion.PROTECT, to='data_map_backend.embeddingspace', verbose_name='Embedding Space'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='generator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_map_backend.generator', verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='trainedclassifier',
            name='embedding_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='data_map_backend.embeddingspace', verbose_name='Embedding Space'),
        ),
    ]
