# Generated by Django 4.2.5 on 2023-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0005_generator_is_preferred_for_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjectfield',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='historicalobjectfield',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar', null=True, verbose_name='Text Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='image_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity an image must have compared to this field to be considered relevant / similar', null=True, verbose_name='Image Similarity Threshold'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='text_similarity_threshold',
            field=models.FloatField(blank=True, help_text='The minimum score / similarity a text must have compared to this field to be considered relevant / similar', null=True, verbose_name='Text Similarity Threshold'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='default_search_fields',
            field=models.ManyToManyField(blank=True, help_text='For combined search', related_name='+', to='data_map_backend.objectfield', verbose_name='Default Search Fields'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='descriptive_text_fields',
            field=models.ManyToManyField(blank=True, help_text='For Word2Vec and Cluster Titles', related_name='+', to='data_map_backend.objectfield', verbose_name='Descriptive Text Fields'),
        ),
    ]
