# Generated by Django 4.2.5 on 2023-10-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0006_historicalobjectfield_image_similarity_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectschema',
            name='primary_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_map_backend.objectfield', verbose_name='Primary Key'),
        ),
    ]
