# Generated by Django 5.0.3 on 2024-04-09 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0006_dataset_is_organization_wide_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('service', models.CharField(max_length=200, verbose_name='Service')),
                ('limit_per_month', models.IntegerField(default=50, verbose_name='Limit')),
                ('usage_per_month', models.JSONField(blank=True, default=dict, null=True, verbose_name='Usage')),
                ('warning_ratio', models.FloatField(default=0.8, verbose_name='Warning Ratio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service Usage',
                'verbose_name_plural': 'Service Usages',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
