# Generated by Django 4.2.5 on 2023-11-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_map_backend', '0007_alter_objectschema_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
            ],
            options={
                'verbose_name': 'Classifier',
                'verbose_name_plural': 'Classifiers',
            },
        ),
        migrations.AddField(
            model_name='historicalobjectfield',
            name='language_analysis',
            field=models.CharField(choices=[('', 'None / Mixed-language'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('czech', 'Czech'), ('russian', 'Russian'), ('hindi', 'Hindi')], default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='objectfield',
            name='language_analysis',
            field=models.CharField(choices=[('', 'None / Mixed-language'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('czech', 'Czech'), ('russian', 'Russian'), ('hindi', 'Hindi')], default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='TEXT', max_length=50, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='output_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='VECTOR', max_length=50, verbose_name='Output Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenerator',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='TEXT', max_length=50, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenerator',
            name='output_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='VECTOR', max_length=50, verbose_name='Output Type'),
        ),
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='TEXT', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IDENTIFIER', 'Identifier'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object')], default='TEXT', max_length=50, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='HistoricalClassifier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(blank=True, editable=False, verbose_name='Changed at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Classifier',
                'verbose_name_plural': 'historical Classifiers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
