# Generated by Django 5.0.3 on 2024-04-09 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0007_serviceusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceusage',
            name='limit_per_month',
        ),
        migrations.RemoveField(
            model_name='serviceusage',
            name='usage_per_month',
        ),
        migrations.AddField(
            model_name='serviceusage',
            name='limit_per_period',
            field=models.IntegerField(default=50, verbose_name='Limit per Period'),
        ),
        migrations.AddField(
            model_name='serviceusage',
            name='period_type',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=50, verbose_name='Period Type'),
        ),
        migrations.CreateModel(
            name='ServiceUsagePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('period', models.CharField(max_length=50, verbose_name='Period')),
                ('usage', models.IntegerField(default=0, verbose_name='Usage')),
                ('service_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_periods', to='data_map_backend.serviceusage', verbose_name='Service Usage')),
            ],
            options={
                'verbose_name': 'Service Usage Period',
                'verbose_name_plural': 'Service Usage Periods',
                'unique_together': {('service_usage', 'period')},
            },
        ),
    ]
