# Generated by Django 4.2.7 on 2023-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0007_remove_dataset_collection_list_rendering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='relevant_object_fields',
            field=models.ManyToManyField(blank=True, help_text="The 'source' fields (text or image) for items from this dataset, using default search fields (or their sources for vectors) if empty", related_name='+', to='data_map_backend.objectfield', verbose_name='Relevant Object Fields'),
        ),
        migrations.AlterField(
            model_name='classifierexample',
            name='classes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Classes'),
        ),
    ]
