# Generated by Django 5.0.4 on 2024-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0008_remove_serviceusage_limit_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this organization is visible to everyone on the internet', verbose_name='Is public'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this organization is visible to everyone on the internet', verbose_name='Is public'),
        ),
    ]
