# Generated by Django 5.0.4 on 2024-04-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0009_historicalorganization_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSearchHistoryItem',
        ),
    ]
