# Generated by Django 4.2.5 on 2023-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0009_alter_historicalobjectfield_language_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjectfield',
            name='language_analysis',
            field=models.CharField(blank=True, choices=[('None', 'None / Mixed-language'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('czech', 'Czech'), ('russian', 'Russian'), ('hindi', 'Hindi')], default='None', max_length=50, null=True, verbose_name='Language Analysis'),
        ),
        migrations.AlterField(
            model_name='objectfield',
            name='language_analysis',
            field=models.CharField(blank=True, choices=[('None', 'None / Mixed-language'), ('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('czech', 'Czech'), ('russian', 'Russian'), ('hindi', 'Hindi')], default='None', max_length=50, null=True, verbose_name='Language Analysis'),
        ),
    ]
