# Generated by Django 4.2.4 on 2023-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0010_historicalobjectschema_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjectschema',
            name='map_rendering',
            field=models.TextField(blank=True, null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='map_rendering',
            field=models.TextField(blank=True, null=True, verbose_name='Rendering (Map)'),
        ),
    ]
