# Generated by Django 5.0.4 on 2024-05-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0012_exportconverter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportconverter',
            name='universally_applicable',
            field=models.BooleanField(default=False, help_text='Whether this converter is applicable to all datasets', verbose_name='Universally Applicable'),
        ),
        migrations.AddField(
            model_name='historicalexportconverter',
            name='universally_applicable',
            field=models.BooleanField(default=False, help_text='Whether this converter is applicable to all datasets', verbose_name='Universally Applicable'),
        ),
    ]
