# Generated by Django 5.0.4 on 2024-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0013_exportconverter_universally_applicable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportconverter',
            name='identifier',
            field=models.CharField(max_length=200, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalexportconverter',
            name='identifier',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Identifier'),
        ),
    ]
