# Generated by Django 4.2.7 on 2024-02-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0014_remove_classifier_dataset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classifierdatasetspecificsettings',
            options={'verbose_name': 'Dataset Specific Settings', 'verbose_name_plural': 'Dataset Specific Settings'},
        ),
        migrations.RemoveField(
            model_name='historicalsearchhistoryitem',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='historicalstoredmap',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='searchhistoryitem',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='storedmap',
            name='dataset',
        ),
        migrations.AddField(
            model_name='historicalsearchhistoryitem',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='historicalstoredmap',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='searchhistoryitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_map_backend.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedmap',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_map_backend.organization', verbose_name='Organization'),
            preserve_default=False,
        ),
    ]
