# Generated by Django 5.0.6 on 2024-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0014_alter_exportconverter_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceusage',
            name='limit_per_period',
            field=models.FloatField(default=50.0, verbose_name='Limit per Period'),
        ),
        migrations.AlterField(
            model_name='serviceusageperiod',
            name='usage',
            field=models.FloatField(default=0, verbose_name='Usage'),
        ),
    ]
