# Generated by Django 4.2.4 on 2023-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0014_alter_historicalitemcollection_negative_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitemcollection',
            name='negative_ids',
            field=models.JSONField(default=list, verbose_name='Negative IDs'),
        ),
        migrations.AlterField(
            model_name='historicalitemcollection',
            name='positive_ids',
            field=models.JSONField(default=list, verbose_name='Positive IDs'),
        ),
        migrations.AlterField(
            model_name='itemcollection',
            name='negative_ids',
            field=models.JSONField(default=list, verbose_name='Negative IDs'),
        ),
        migrations.AlterField(
            model_name='itemcollection',
            name='positive_ids',
            field=models.JSONField(default=list, verbose_name='Positive IDs'),
        ),
    ]
