# Generated by Django 4.2.4 on 2023-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0015_alter_historicalitemcollection_negative_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstoredmap',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storedmap',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
