# Generated by Django 4.2.7 on 2024-02-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0017_historicalstoredmap_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='related_organization',
            field=models.ForeignKey(blank=True, help_text='Classifiers can be used across organizations, but they usually belong to one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_map_backend.organization', verbose_name='Related Organization'),
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='related_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Classifiers can be used across organizations, but they usually belong to one', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.organization', verbose_name='Related Organization'),
        ),
    ]
