# Generated by Django 4.2.5 on 2023-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0017_alter_historicalobjectschema_result_list_rendering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.RemoveField(
            model_name='objectschema',
            name='detail_view_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Detail View)'),
        ),
        migrations.RemoveField(
            model_name='objectschema',
            name='hover_label_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Hover Label)'),
        ),
        migrations.RemoveField(
            model_name='objectschema',
            name='map_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"point_size_field\\": \\"(item) => { return null }\\",\\n\\"point_color_field\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.RemoveField(
            model_name='objectschema',
            name='result_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Result List)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='detail_view_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Detail View)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='hover_label_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Hover Label)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='map_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"point_size_field\\": \\"(item) => { return null }\\",\\n\\"point_color_field\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.AddField(
            model_name='historicalobjectschema',
            name='result_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Result List)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='detail_view_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Detail View)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='hover_label_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Hover Label)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='map_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"point_size_field\\": \\"(item) => { return null }\\",\\n\\"point_color_field\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='result_list_rendering',
            field=models.JSONField(blank=True, default='"{\\n\\"required_fields\\": [],\\n\\"title\\": \\"(item) => { return null }\\",\\n\\"subtitle\\": \\"(item) => { return null }\\",\\n\\"body\\": \\"(item) => { return null }\\",\\n\\"image\\": \\"(item) => { return null }\\",\\n\\"url\\": \\"(item) => { return null }\\"\\n}"', null=True, verbose_name='Rendering (Result List)'),
        ),
    ]
