# Generated by Django 5.0.6 on 2024-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0017_switch_to_custom_user_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_cookies',
            field=models.BooleanField(default=False, verbose_name='Cookies accepted'),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_emails',
            field=models.BooleanField(default=False, verbose_name='Emails allowed'),
        ),
    ]
