# Generated by Django 4.2.5 on 2023-09-06 12:00

import data_map_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0018_alter_historicalobjectschema_collection_list_rendering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalobjectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_collection_list_rendering, null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.AlterField(
            model_name='historicalobjectschema',
            name='detail_view_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_detail_view_rendering, null=True, verbose_name='Rendering (Detail View)'),
        ),
        migrations.AlterField(
            model_name='historicalobjectschema',
            name='hover_label_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_hover_label_rendering, null=True, verbose_name='Rendering (Hover Label)'),
        ),
        migrations.AlterField(
            model_name='historicalobjectschema',
            name='map_rendering',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.AlterField(
            model_name='historicalobjectschema',
            name='result_list_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_result_list_rendering, null=True, verbose_name='Rendering (Result List)'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='collection_list_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_collection_list_rendering, null=True, verbose_name='Rendering (Collection List)'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='detail_view_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_detail_view_rendering, null=True, verbose_name='Rendering (Detail View)'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='hover_label_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_hover_label_rendering, null=True, verbose_name='Rendering (Hover Label)'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='map_rendering',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Rendering (Map)'),
        ),
        migrations.AlterField(
            model_name='objectschema',
            name='result_list_rendering',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_result_list_rendering, null=True, verbose_name='Rendering (Result List)'),
        ),
    ]
