# Generated by Django 5.0.2 on 2024-02-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0018_classifier_related_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='examples_last_changed',
            field=models.JSONField(blank=True, default=dict, help_text='For each class, the last time an example was added or removed', null=True, verbose_name='Examples Last Changed'),
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='examples_last_changed',
            field=models.JSONField(blank=True, default=dict, help_text='For each class, the last time an example was added or removed', null=True, verbose_name='Examples Last Changed'),
        ),
    ]
