# Generated by Django 5.0.2 on 2024-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0019_classifier_examples_last_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='trained_classifiers',
            field=models.JSONField(blank=True, default=dict, help_text="For each embedding space, and there for each class, a 'decision' vector to be applied with dotproduct (plus time_updated)", null=True, verbose_name='Trained Classifiers'),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='trained_classifiers',
            field=models.JSONField(blank=True, default=dict, help_text="For each embedding space, and there for each class, a 'decision' vector to be applied with dotproduct (plus time_updated)", null=True, verbose_name='Trained Classifiers'),
        ),
    ]
