# Generated by Django 4.2.5 on 2023-09-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0019_alter_historicalobjectschema_collection_list_rendering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobjectschema',
            name='map_rendering',
        ),
        migrations.RemoveField(
            model_name='objectschema',
            name='map_rendering',
        ),
    ]
