# Generated by Django 4.2.5 on 2023-09-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0020_remove_historicalobjectschema_map_rendering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectschema',
            name='descriptive_text_fields',
            field=models.ManyToManyField(blank=True, help_text='For Word2Vec and Cluster Titles', null=True, related_name='+', to='data_map_backend.objectfield', verbose_name='Descriptive Text Fields'),
        ),
    ]
