# Generated by Django 5.0.2 on 2024-02-22 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0020_alter_classifier_trained_classifiers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classifier',
            new_name='DataCollection',
        ),
        migrations.RenameModel(
            old_name='HistoricalClassifier',
            new_name='HistoricalDataCollection',
        ),
    ]
