# Generated by Django 5.0.2 on 2024-02-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0021_rename_classifier_datacollection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassifierDatasetSpecificSettings',
            new_name='DatasetSpecificSettingsOfCollection',
        ),
    ]
