# Generated by Django 5.0.2 on 2024-02-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0023_historicaldatasetspecificsettingsofcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassifierExample',
            new_name='CollectionItem',
        ),
    ]
