# Generated by Django 5.0.2 on 2024-02-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0025_remove_itemcollection_dataset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'verbose_name': 'Collection Item', 'verbose_name_plural': 'Collection Item'},
        ),
        migrations.AlterModelOptions(
            name='datacollection',
            options={'verbose_name': 'Data Collection', 'verbose_name_plural': 'Data Collections'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatacollection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Data Collection', 'verbose_name_plural': 'historical Data Collections'},
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='examples_last_changed',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='parent_classifiers',
        ),
        migrations.RemoveField(
            model_name='historicaldatacollection',
            name='examples_last_changed',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_map_backend.datacollection', verbose_name='Collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacollection',
            name='items_last_changed',
            field=models.JSONField(blank=True, default=dict, help_text='For each class, the last time an item was added or removed', null=True, verbose_name='Items Last Changed'),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='parent_collection',
            field=models.ManyToManyField(blank=True, to='data_map_backend.datacollection', verbose_name='Parent Collection'),
        ),
        migrations.AddField(
            model_name='historicaldatacollection',
            name='items_last_changed',
            field=models.JSONField(blank=True, default=dict, help_text='For each class, the last time an item was added or removed', null=True, verbose_name='Items Last Changed'),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='related_organization',
            field=models.ForeignKey(blank=True, help_text='Collections can be used across organizations, but they usually belong to one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_map_backend.organization', verbose_name='Related Organization'),
        ),
        migrations.AlterField(
            model_name='datasetspecificsettingsofcollection',
            name='classifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_specific_settings', to='data_map_backend.datacollection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='historicaldatacollection',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='historicaldatacollection',
            name='related_organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Collections can be used across organizations, but they usually belong to one', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.organization', verbose_name='Related Organization'),
        ),
        migrations.AlterField(
            model_name='historicaldatasetspecificsettingsofcollection',
            name='classifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_map_backend.datacollection', verbose_name='Collection'),
        ),
    ]
