# Generated by Django 5.0.2 on 2024-02-22 12:13

import data_map_backend.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0026_alter_collectionitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='classes',
            field=models.JSONField(default=data_map_backend.models.class_field_default, verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='datacollection',
            name='class_names',
            field=models.JSONField(blank=True, default=data_map_backend.models.class_field_default, help_text="If empty, either deducted from classes or if data doesn't have classed, converted classifier name is used", null=True, verbose_name='Class Names'),
        ),
        migrations.AlterField(
            model_name='historicaldatacollection',
            name='class_names',
            field=models.JSONField(blank=True, default=data_map_backend.models.class_field_default, help_text="If empty, either deducted from classes or if data doesn't have classed, converted classifier name is used", null=True, verbose_name='Class Names'),
        ),
    ]
