# Generated by Django 5.0.2 on 2024-02-23 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0028_rename_classifier_example_rendering_dataset_collection_item_rendering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrainedclassifier',
            name='last_retrained_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Retrained at'),
        ),
        migrations.AddField(
            model_name='trainedclassifier',
            name='last_retrained_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Retrained at'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date added'),
        ),
    ]
