# Generated by Django 5.0.3 on 2024-03-14 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0035_alter_dataset_defaults_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, verbose_name='Class')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date added')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('chat_history', models.JSONField(blank=True, default=list, null=True, verbose_name='Chat History')),
                ('is_processing', models.BooleanField(default=False, verbose_name='Is Processing')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_map_backend.datacollection', verbose_name='Collection')),
            ],
        ),
    ]
