# Generated by Django 5.0.3 on 2024-03-14 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0036_collectionchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionchat',
            name='date_added',
        ),
        migrations.AddField(
            model_name='collectionchat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created at'),
        ),
    ]
