# Generated by Django 5.0.3 on 2024-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0037_remove_collectionchat_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='extraction_questions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Extraction Questions'),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Table Columns'),
        ),
        migrations.AddField(
            model_name='historicaldatacollection',
            name='extraction_questions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Extraction Questions'),
        ),
        migrations.AddField(
            model_name='historicaldatacollection',
            name='table_columns',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Table Columns'),
        ),
    ]
