# Generated by Django 5.0.3 on 2024-03-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0038_datacollection_extraction_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='extraction_answers',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Extraction Answers'),
        ),
    ]
