# Generated by Django 5.0.3 on 2024-03-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0039_collectionitem_extraction_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='current_extraction_processes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Current Extraction Processes'),
        ),
        migrations.AddField(
            model_name='historicaldatacollection',
            name='current_extraction_processes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Current Extraction Processes'),
        ),
    ]
