export const products = [
  {
    category: "Search + Curate",
    products: [
      {
        slug: "tender-hub",
        product_name: "Tender Hub",
        use_case: "Search for Public Tenders",
        bullets: [
          "Platform to search for public tenders in Germany",
          "Personalized e-mail newsletter using AI",
          "Built together with ENDA GmbH",
          "Available to everyone for free",
        ],
        description: "Tender Hub is a platform for searching for public tenders from all over the world. You can filter tenders by country, sector, and more. You can also get notified when new tenders are published.",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "Free to use",
        call_to_action_link: "https://tenders.enda.eu",
      },
      {
        slug: "absclust",
        product_name: "AbsClust",
        use_case: "Search in 200M Scientific Articles",
        bullets: [
          "Platform to search for scientific articles",
          "Available to everyone for free",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "Free to use",
        call_to_action_link: "https://v2.absclust.com",
      },
      {
        slug: "custom-search-product",
        product_name: "Custom Product",
        use_case: "You want to search your archive of data?",
        bullets: [
          "We can build a custom product for you",
          "Our technology can integrate with almost any archive in days",
          "Providing you with next-gen AI features with your data",
          "Contact us for more information",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "Starting from 2000€",
        call_to_action_link: null,
      },
    ],
  },
  {
    category: "Extract + Explain",
    products: [
      {
        slug: "fact-collector",
        product_name: "Fact Collector",
        use_case: "Gather complete lists of machine parts, people etc. from technical documents",
        bullets: [
          "Extracts all facts from technical documents, e.g. flow charts, manuals, CAD files, project reports etc.",
          "Solves the issue of time consuming manual data extraction, e.g. for security audits, compliance checks, etc.",
          "In contrast to AI chats like Micorsoft Copilot, our solution is reliable and provides complete lists of facts",
          "Integrates with your documents and workflows",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: "https://tenders.enda.eu",
      },
      {
        slug: "project-management-copilot",
        product_name: "Project Management Copilot",
        use_case: "Answer questions and provide overviews of industrial projects",
        bullets: [
          "Answer questions about industrial projects, e.g. project status, budget, timeline, etc.",
          "Integrates with local files",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: "https://tenders.enda.eu",
      },
    ],
  },
  {
    category: "Process & Automate",
    products: [
      {
        slug: "market-research-hub",
        product_name: "Market Research Hub",
        use_case: "Analyze qualitative market research interviews using AI",
        bullets: [
          "Just upload your audio files or transcriptions",
          "Extract information from each interview using AI in a smart table",
          "Reduce time to analyze interviews by 90%",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: null,
      },
      {
        slug: "content-moderation",
        product_name: "Content Moderation",
        use_case: "Check user content like images, audio and text for inappropriate content",
        bullets: [
          "Highly customizable content moderation",
          "Define your criteria in minutes instead of hours",
          "Works with any type of content",
          "Very cheap even for large volumes",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: null,
      },
      {
        slug: "metadata-enrichment",
        product_name: "Metadata Enrichment",
        use_case: "Auto-generate metadata for images and videos",
        bullets: [
          "Assign tags, subtitles and categories to your images and videos",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: null,
      },
      {
        slug: "contract-checker",
        product_name: "Contract Checker",
        use_case: "Check contracts for compliance with your company's rules",
        bullets: [
          "Upload your contracts and define your rules",
          "Get a report on which contracts are compliant and which are not",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: null,
      },
      {
        slug: "property-checker",
        product_name: "Property Checker",
        use_case: "Automate your real estate due diligence",
        bullets: [
          "Upload your real estate documents",
          "Get a report on the property's compliance with your rules",
        ],
        description: "",
        video_url: "https://www.youtube.com/embed/1Q3w3Qe3j4A",
        cost: "From 500€ / month",
        call_to_action_link: null,
      },
    ],
  },
]
