# Generated by Django 5.0.6 on 2024-07-04 13:33

import data_map_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0011_datasetfield_additional_language_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncolumn',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='TEXT', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='TEXT', help_text='Either IDENTIFIER, TEXT, IMAGE', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='database_name',
            field=models.CharField(blank=True, default=data_map_backend.models.generate_unique_database_name, help_text="Name of the OpenSearch index and vector DB prefix, using 'dataset_&lt;id&gt;' if empty", max_length=100, null=True, verbose_name='Database Name'),
        ),
        migrations.AlterField(
            model_name='datasetfield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='TEXT', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='TEXT', max_length=50, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='output_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='VECTOR', max_length=50, verbose_name='Output Type'),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='database_name',
            field=models.CharField(blank=True, default=data_map_backend.models.generate_unique_database_name, help_text="Name of the OpenSearch index and vector DB prefix, using 'dataset_&lt;id&gt;' if empty", max_length=100, null=True, verbose_name='Database Name'),
        ),
        migrations.AlterField(
            model_name='historicalgenerator',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='TEXT', max_length=50, verbose_name='Input Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenerator',
            name='output_type',
            field=models.CharField(choices=[('TEXT', 'Prose Text'), ('STRING', 'Exact String'), ('IDENTIFIER', 'Identifier / ID'), ('FLOAT', 'Float'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('DATETIME', 'Datetime'), ('TIME', 'Time'), ('VECTOR', 'Vector'), ('CLASS_PROBABILITY', 'Class Probability'), ('FACE', 'Face'), ('URL', 'URL'), ('GEO_COORDINATES', 'Geo Coordinates'), ('TAG', 'Tag / Keyword / Category'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('FOREIGN_KEY', 'Reference to other element'), ('BOOL', 'Bool'), ('ATTRIBUTES', 'Attributes (dict)'), ('ARBITRARY_OBJECT', 'Non-indexed object'), ('CHUNK', 'Text Chunk with Metadata')], default='VECTOR', max_length=50, verbose_name='Output Type'),
        ),
    ]
