# Generated by Django 5.0.6 on 2024-07-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0013_alter_datasetfield_index_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetfield",
            name="index_parameters",
            field=models.JSONField(blank=True, default=dict, verbose_name="Index Parameters"),
        ),
    ]
