# Generated by Django 5.0.6 on 2024-08-25 16:47

from django.db import migrations

# See here: https://code.djangoproject.com/ticket/25313#comment:24


def change_user_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ct = ContentType.objects.filter(app_label="auth", model="user").first()
    if ct:
        ct.app_label = "user"
        ct.save()


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0016_searchhistoryitem_auto_relaxed_and_more"),
    ]

    operations = [
        migrations.RunPython(change_user_type),
    ]
