# Generated by Django 5.0.6 on 2024-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0022_collectioncolumn_auto_run_for_approved_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='relevance',
            field=models.IntegerField(default=3, help_text='From +3 to -3. 0 is a new, non-reviewed candidate', verbose_name='Relevance'),
        ),
    ]
