# Generated by Django 5.0.6 on 2024-10-08 14:17

from django.db import migrations, models

import data_map_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0028_alter_collectionitem_dataset_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="classes",
            field=models.JSONField(
                db_index=True, default=data_map_backend.models.class_field_default, verbose_name="Classes"
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="search_source_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID of the search source that generated this item",
                max_length=50,
                null=True,
                verbose_name="Search Source ID",
            ),
        ),
    ]
