# Generated by Django 5.0.6 on 2024-10-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0029_alter_collectionitem_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollection",
            name="explanation_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of explanations what was done (e.g. using AI)",
                verbose_name="Explanation Log",
            ),
        ),
        migrations.AddField(
            model_name="historicaldatacollection",
            name="explanation_log",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of explanations what was done (e.g. using AI)",
                verbose_name="Explanation Log",
            ),
        ),
        migrations.AlterField(
            model_name="datasetschema",
            name="identifier",
            field=models.CharField(
                help_text="Do not change this after being used elsewhere (or after creating fields, its the PK)",
                max_length=200,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Identifier",
            ),
        ),
    ]
