# Generated by Django 5.0.6 on 2024-10-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0030_datacollection_explanation_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacollection",
            name="map_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Map Data"),
        ),
        migrations.AddField(
            model_name="historicaldatacollection",
            name="map_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Map Data"),
        ),
    ]
