# Generated by Django 5.0.6 on 2024-11-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0033_alter_collectioncolumn_parameters_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectioncolumn",
            name="determines_relevance",
        ),
    ]
