# Generated by Django 5.0.6 on 2024-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0035_dataset_filter_prompts_datasetschema_filter_prompts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='filters',
            field=models.JSONField(blank=True, default=list, help_text='Visibility filters', verbose_name='Filters'),
        ),
        migrations.AddField(
            model_name='historicaldatacollection',
            name='filters',
            field=models.JSONField(blank=True, default=list, help_text='Visibility filters', verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='datasetfield',
            name='language_analysis',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('czech', 'Czech'), ('russian', 'Russian'), ('hindi', 'Hindi')], help_text="Only applicable for 'Text' and 'Exact String' fields", max_length=50, null=True, verbose_name='Language Processing'),
        ),
    ]
