# Generated by Django 5.0.6 on 2024-12-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0041_datacollection_ui_settings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDataCollection',
        ),
    ]
