# Generated by Django 5.0.6 on 2025-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0045_generationtask_stop_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetschema",
            name="all_parents",
            field=models.CharField(
                blank=True,
                help_text="Field that contains the PKs of all parents as an array",
                max_length=200,
                null=True,
                verbose_name="All Parents",
            ),
        ),
        migrations.AddField(
            model_name="datasetschema",
            name="direct_parent",
            field=models.CharField(
                blank=True,
                help_text="Field that contains the PK of the direct parent",
                max_length=200,
                null=True,
                verbose_name="Direct Parent",
            ),
        ),
        migrations.AddField(
            model_name="datasetschema",
            name="is_group_field",
            field=models.CharField(
                blank=True,
                help_text="Bool field that indicates if the item can have children",
                max_length=200,
                null=True,
                verbose_name="Is Group Field",
            ),
        ),
        migrations.AlterField(
            model_name="generationtask",
            name="clear_all_output_fields",
            field=models.BooleanField(
                default=False,
                help_text="Clear all output fields (for multi-output generators) before re-generating all items",
                verbose_name="Clear all output fields",
            ),
        ),
    ]
