# Generated by Django 5.0.6 on 2025-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0047_datacollection_search_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingtask',
            name='class_name',
            field=models.CharField(default='_default', max_length=200, verbose_name='Class'),
        ),
    ]
