# Generated by Django 5.0.6 on 2025-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0048_alter_writingtask_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='workspace_tool_intro_text',
            new_name='tool_intro_text',
        ),
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='workspace_tool_logo_url',
            new_name='tool_logo_url',
        ),
        migrations.RenameField(
            model_name='historicalorganization',
            old_name='workspace_tool_title',
            new_name='tool_title',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='workspace_tool_intro_text',
            new_name='tool_intro_text',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='workspace_tool_logo_url',
            new_name='tool_logo_url',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='workspace_tool_title',
            new_name='tool_title',
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='domains',
            field=models.JSONField(blank=True, default=list, help_text='List of domains where this organization is visible', verbose_name='Domains'),
        ),
        migrations.AddField(
            model_name='organization',
            name='domains',
            field=models.JSONField(blank=True, default=list, help_text='List of domains where this organization is visible', verbose_name='Domains'),
        ),migrations.AddField(
            model_name='historicalorganization',
            name='tool_accent_color',
            field=models.CharField(blank=True, help_text='Accent color of the tool in the frontend, e.g. #ff0000', max_length=7, null=True, verbose_name='Tool Accent Color (Hex)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tool_accent_color',
            field=models.CharField(blank=True, help_text='Accent color of the tool in the frontend, e.g. #ff0000', max_length=7, null=True, verbose_name='Tool Accent Color (Hex)'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='tool_intro_text',
            field=models.TextField(blank=True, help_text='Intro text of the tool, HTML is allowed', null=True, verbose_name='Tool Intro Text'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='tool_logo_url',
            field=models.CharField(blank=True, help_text='URL of the tool logo in the frontend', max_length=200, null=True, verbose_name='Tool Logo URL'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='tool_title',
            field=models.CharField(blank=True, help_text='Title of the tool in the frontend', max_length=80, null=True, verbose_name='Tool Title'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tool_intro_text',
            field=models.TextField(blank=True, help_text='Intro text of the tool, HTML is allowed', null=True, verbose_name='Tool Intro Text'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tool_logo_url',
            field=models.CharField(blank=True, help_text='URL of the tool logo in the frontend', max_length=200, null=True, verbose_name='Tool Logo URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tool_title',
            field=models.CharField(blank=True, help_text='Title of the tool in the frontend', max_length=80, null=True, verbose_name='Tool Title'),
        ),
    ]
