# Generated by Django 5.0.6 on 2025-01-15 14:29

import data_map_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0049_organization_domains_and_whitelabeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetschema',
            name='translated_entity_name',
            field=models.JSONField(blank=True, default=data_map_backend.models.get_default_translated_entity_name, help_text="Translations of the entity name, e.g. {'singular': {'de': 'Produkt', 'fr': 'Produit'}, 'plural': {'de': 'Produkte', 'fr': 'Produits'}}", verbose_name='Translated Entity Name'),
        ),
    ]
