# Generated by Django 5.0.6 on 2025-01-21 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0052_prepare_search_rework_by_converting_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollection',
            name='last_search_task',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='search_sources',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='search_tasks',
        ),
        migrations.AddField(
            model_name='datacollection',
            name='search_mode',
            field=models.BooleanField(default=False, help_text='Whether this collection is currently in search mode (see most recent search task)', verbose_name='Search Mode'),
        ),
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Settings for the search task', verbose_name='Settings')),
                ('retrieval_parameters', models.JSONField(blank=True, default=dict, help_text='Parameters for retrieval (partly generated from user input)', verbose_name='Retrieval Parameters')),
                ('last_retrieval_status', models.JSONField(blank=True, default=dict, help_text='Status of the last retrieval (available results, retrieved results, relaxation etc.)', verbose_name='Last Retrieval Status')),
                ('is_saved', models.BooleanField(default=False, help_text='Whether the search task is saved', verbose_name='Is saved')),
                ('run_on_new_items', models.BooleanField(default=False, help_text='Whether the search task should be run on new items', verbose_name='Run on new items')),
                ('run_periodically', models.BooleanField(default=False, help_text='Whether the search task should be run periodically', verbose_name='Run periodically')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start of the period for periodic runs', null=True, verbose_name='Period start')),
                ('period_interval', models.DurationField(blank=True, help_text='Interval for periodic runs', null=True, verbose_name='Period interval')),
                ('last_run', models.DateTimeField(blank=True, help_text='Last time the search task was run', null=True, verbose_name='Last run')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_tasks', to='data_map_backend.datacollection', verbose_name='Collection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_map_backend.dataset', verbose_name='Dataset')),
            ],
            options={
                'verbose_name': 'Search Task',
                'verbose_name_plural': 'Search Tasks',
            },
        ),
        migrations.AddField(
            model_name='datacollection',
            name='most_recent_search_task',
            field=models.ForeignKey(blank=True, help_text='(is the active one if in search mode, otherwise the last one)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_map_backend.searchtask', verbose_name='Most Recent Search Task'),
        ),
    ]
