# Generated by Django 5.0.6 on 2025-01-22 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0054_datacollection_search_task_navigation_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtask",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at"),
        ),
    ]
