# Generated by Django 5.0.6 on 2025-01-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0055_searchtask_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="writingtask",
            old_name="module",
            new_name="model",
        ),
        migrations.RenameField(
            model_name="writingtask",
            old_name="prompt",
            new_name="expression",
        ),
        migrations.AddField(
            model_name="writingtask",
            name="include_previous_tasks",
            field=models.BooleanField(
                default=True, help_text="Allows for a chat-like experience", verbose_name="Include Previous Tasks"
            ),
        ),
        migrations.AddField(
            model_name="writingtask",
            name="prompt_template",
            field=models.TextField(
                blank=True,
                help_text="Template for the prompt if this column uses an LLM. If empty, a default template is used. There are some special variables like {{ context }} and {{ expression }} that can be used.",
                null=True,
                verbose_name="Prompt Template",
            ),
        ),
        migrations.AlterField(
            model_name="writingtask",
            name="model",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="LLM Model"),
        ),
        migrations.AlterField(
            model_name="writingtask",
            name="expression",
            field=models.TextField(blank=True, null=True, verbose_name="Task / Question"),
        ),
    ]
