# Generated by Django 5.0.6 on 2025-01-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0056_change_writing_task_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingtask",
            name="parameters",
            field=models.JSONField(blank=True, default=dict, verbose_name="Parameters"),
        ),
    ]
