# Generated by Django 5.0.6 on 2025-02-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_map_backend", "0059_alter_chat_chat_history_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoredMap",
        ),
    ]
