# Generated by Django 5.0.6 on 2025-02-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0060_delete_storedmap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
