# Generated by Django 5.1.6 on 2025-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0062_dataset_is_available_to_groups_and_more'),
        ('data_map_backend', '0062_dataset_languages_historicaldataset_languages'),
    ]

    operations = [
    ]
