# Generated by Django 5.2.5 on 2025-08-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0063_merge_20250409_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfield',
            name='source_fields',
            field=models.JSONField(blank=True, default=list, help_text="List of source field identifiers, or dict generator input -> source field.Use prefix 'dep:' to indicate a dependency-only field, which is not passed to the generator function", null=True, verbose_name='Source Fields'),
        ),
    ]
