# Generated by Django 4.2.4 on 2023-08-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0003_alter_objectfield_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectfield',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_fields', to='data_map_backend.objectschema', verbose_name='Schema'),
        ),
    ]
