# Generated by Django 4.2.4 on 2023-08-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0007_alter_generator_input_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobjectfield',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='objectfield',
            name='is_required',
        ),
    ]
