# Generated by Django 4.2.4 on 2023-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_map_backend', '0009_alter_historicalobjectfield_generating_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjectschema',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='objectschema',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Description'),
        ),
    ]
