from django.urls import path

from .views import other_views, question_views

urlpatterns = [
    path("health", other_views.get_health),
    path("get_current_user", other_views.get_current_user),
    path("set_user_preferences", other_views.set_user_preferences_route),
    path("available_organizations", other_views.get_available_organizations),
    path("dataset", other_views.get_dataset),
    path("add_search_history_item", other_views.add_search_history_item),
    path("update_search_history_item", other_views.update_search_history_item),
    path("add_collection", other_views.add_collection),
    path("get_collections", other_views.get_collections),
    path("get_collection", other_views.get_collection),
    path("set_collection_attributes", other_views.set_collection_attributes),
    path("get_trained_classifier", other_views.get_trained_classifier),
    path("set_trained_classifier", other_views.set_trained_classifier),
    path("get_collection_items", other_views.get_collection_items),
    path("get_related_collection_items", other_views.get_related_collection_items),
    path("delete_collection", other_views.delete_collection),
    path("add_item_to_collection", other_views.add_item_to_collection),
    path("set_collection_item_relevance", other_views.set_collection_item_relevance),
    path("remove_collection_item", other_views.remove_collection_item),
    path("remove_collection_item_by_value", other_views.remove_collection_item_by_value),
    path("remove_items", other_views.remove_items),
    path("get_dataset_schemas", other_views.get_dataset_schemas),
    path("create_dataset_from_schema", other_views.create_dataset_from_schema),
    path("get_or_create_default_dataset", other_views.get_or_create_default_dataset_route),
    path("change_dataset", other_views.change_dataset),
    path("delete_dataset", other_views.delete_dataset),
    path("get_import_converter", other_views.get_import_converter),
    path("get_export_converter", other_views.get_export_converter),
    path("track_service_usage", question_views.track_service_usage),
    path("get_service_usage", question_views.get_service_usage),
]
