from django.urls import path
from . import views
from . import question_views

urlpatterns=[
    path("health", views.get_health),
    path("get_current_user", views.get_current_user),
    path("available_organizations", views.get_available_organizations),
    path("dataset", views.get_dataset),
    path("available_datasets", views.get_available_datasets),
    path("add_search_history_item", views.add_search_history_item),
    path("get_search_history", views.get_search_history),
    path("add_collection", views.add_collection),
    path("add_collection_class", views.add_collection_class),
    path("delete_collection_class", views.delete_collection_class),
    path("get_collections", views.get_collections),
    path("get_collection", views.get_collection),
    path("get_trained_classifier", views.get_trained_classifier),
    path("set_trained_classifier", views.set_trained_classifier),
    path("get_collection_items", views.get_collection_items),
    path("delete_collection", views.delete_collection),
    path("add_item_to_collection", views.add_item_to_collection),
    path("remove_collection_item", views.remove_collection_item),
    path("remove_collection_item_by_value", views.remove_collection_item_by_value),
    path("add_stored_map", views.add_stored_map),
    path("get_stored_maps", views.get_stored_maps),
    path("stored_map_data", views.get_stored_map_data),
    path("delete_stored_map", views.delete_stored_map),
    path("get_generators", views.get_generators),
    path("add_collection_class_chat", question_views.add_collection_class_chat),
    path("add_chat_question", question_views.add_chat_question),
    path("get_collection_class_chats", question_views.get_collection_class_chats),
    path("get_chat_by_id", question_views.get_chat_by_id),
    path("add_collection_extraction_question", question_views.add_collection_extraction_question),
    path("extract_question_from_collection_class_items", question_views.extract_question_from_collection_class_items),
    path("remove_collection_class_extraction_results", question_views.remove_collection_class_extraction_results),
    path("get_dataset_templates", views.get_dataset_templates),
    path("create_dataset_from_template", views.create_dataset_from_template),
    path("delete_dataset", views.delete_dataset),
    path("get_import_converter", views.get_import_converter),
]
