name: Publish docs via GitHub Pages
on:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r docs/requirements.txt
      - run: mkdocs build
        working-directory: docs/
      - name: Upload WebDAV
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=${{ secrets.WEBDAV_ENDPOINT }}
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/
          include: 'docs/site/**'
